import { Download, Filter, Plus, Upload } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { useCRM } from "../store";
import type { Deal, Priority } from "../types";
import { Modal } from "../components/Modal";

const money = (n: number) => new Intl.NumberFormat("ru-RU", { notation: "compact", style: "currency", currency: "KZT", maximumFractionDigits: 0 }).format(n);
const priorityLabel: Record<Priority,string> = { low: "Низкий", normal: "Обычный", high: "Высокий", urgent: "Срочный" };
export function Deals({ query, onSelect }: { query: string; onSelect: (d: Deal) => void }) {
  const { state, addDeal, updateDeal, replaceDeals } = useCRM(); const [pipelineId, setPipelineId] = useState(state.pipelines[0].id); const [create, setCreate] = useState(false); const [priority, setPriority] = useState<string>(""); const file = useRef<HTMLInputElement>(null);
  const pipeline = state.pipelines.find(p => p.id === pipelineId) || state.pipelines[0];
  const deals = useMemo(() => state.deals.filter(d => d.pipelineId === pipeline.id && (!query || `${d.clientName} ${d.title} ${d.phone} ${d.email}`.toLowerCase().includes(query.toLowerCase())) && (!priority || d.priority === priority)), [state.deals, pipeline.id, query, priority]);
  const exportData = (xlsx = false) => { const rows = deals.map(d => ({ Клиент:d.clientName, Сделка:d.title, Телефон:d.phone, Email:d.email, Сумма:d.amount, Этап:pipeline.stages.find(s=>s.id===d.stageId)?.name, Приоритет:priorityLabel[d.priority] })); const sheet=XLSX.utils.json_to_sheet(rows); if(xlsx){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,"Сделки");XLSX.writeFile(wb,"leadflow-deals.xlsx");}else{const blob=new Blob(["\ufeff"+XLSX.utils.sheet_to_csv(sheet)],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="leadflow-deals.csv";a.click();}};
  const importFile = async (f: File) => { const wb=XLSX.read(await f.arrayBuffer()); const rows=XLSX.utils.sheet_to_json<Record<string,string|number>>(wb.Sheets[wb.SheetNames[0]]); const incoming=rows.map((r,i):Deal=>({id:crypto.randomUUID(),clientName:String(r["Клиент"]||r["name"]||`Импорт ${i+1}`),title:String(r["Сделка"]||r["title"]||"Новая сделка"),phone:String(r["Телефон"]||r["phone"]||""),email:String(r["Email"]||r["email"]||""),amount:Number(r["Сумма"]||r["amount"]||0),pipelineId:pipeline.id,stageId:pipeline.stages[0].id,priority:"normal",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),assigneeId:state.users[0].id,tagIds:[],comments:[],events:[{id:crypto.randomUUID(),text:"Импортирована из файла",createdAt:new Date().toISOString()}],custom:{}})); const phones=new Set(state.deals.map(d=>d.phone.replace(/\D/g,""))); const unique=incoming.filter(d=>!phones.has(d.phone.replace(/\D/g,""))); replaceDeals([...unique,...state.deals]); alert(`Импортировано: ${unique.length}. Возможных дублей пропущено: ${incoming.length-unique.length}.`); };
  return <><div className="page-head"><div><span className="eyebrow">Рабочее пространство</span><h1>Сделки</h1></div><div className="head-actions"><input ref={file} type="file" hidden accept=".csv,.xlsx,.xls" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><button className="button ghost" onClick={()=>file.current?.click()}><Upload/>Импорт</button><button className="button ghost" onClick={()=>exportData(false)}><Download/>CSV</button><button className="button ghost" onClick={()=>exportData(true)}><Download/>XLSX</button><button className="button" onClick={()=>setCreate(true)}><Plus/>Новая сделка</button></div></div>
    <div className="deals-toolbar"><div className="pipeline-tabs">{state.pipelines.map(p=><button key={p.id} className={p.id===pipeline.id?"active":""} onClick={()=>setPipelineId(p.id)}>{p.name}<span>{state.deals.filter(d=>d.pipelineId===p.id).length}</span></button>)}</div><label className="filter"><Filter/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Все приоритеты</option><option value="urgent">Срочные</option><option value="high">Высокие</option><option value="normal">Обычные</option><option value="low">Низкие</option></select></label></div>
    <div className="kanban">{pipeline.stages.map(stage=>{const cards=deals.filter(d=>d.stageId===stage.id);return <section className="column" key={stage.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("deal");if(id)updateDeal(id,{stageId:stage.id},`Этап изменён на «${stage.name}»`);}}><div className="column-head"><div><i style={{background:stage.color}}/><strong>{stage.name}</strong><span>{cards.length}</span></div><small>{money(cards.reduce((s,d)=>s+d.amount,0))}</small></div><div className="cards">{cards.map(deal=><article draggable onDragStart={e=>e.dataTransfer.setData("deal",deal.id)} className={`deal-card priority-${deal.priority}`} key={deal.id} onClick={()=>onSelect(deal)}><div className="deal-top"><strong>{deal.clientName}</strong><span>{money(deal.amount)}</span></div><p>{deal.title}</p><small>{deal.phone}</small><div className="deal-tags">{deal.tagIds.slice(0,2).map(id=>{const t=state.tags.find(x=>x.id===id);return t&&<span key={id} style={{color:t.color,background:`${t.color}18`}}>{t.name}</span>})}</div>{deal.nextContact&&<div className={new Date(deal.nextContact)<new Date()?"contact overdue":"contact"}>{new Date(deal.nextContact).toLocaleDateString("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}<b>{priorityLabel[deal.priority]}</b></div>}</article>)}{cards.length===0&&<div className="empty-col">Перетащите сделку сюда</div>}</div></section>})}</div>
    {create&&<CreateDeal pipeline={pipeline} onClose={()=>setCreate(false)} onCreate={addDeal}/>}</>;
}
function CreateDeal({pipeline,onClose,onCreate}:{pipeline:ReturnType<typeof useCRM>["state"]["pipelines"][number];onClose:()=>void;onCreate:ReturnType<typeof useCRM>["addDeal"]}){const [v,setV]=useState({clientName:"",title:"",phone:"",amount:""});return <Modal title="Новая сделка" onClose={onClose}><form className="modal-form" onSubmit={e=>{e.preventDefault();onCreate({...v,amount:+v.amount,pipelineId:pipeline.id,stageId:pipeline.stages[0].id});onClose();}}><label>Имя клиента<input required autoFocus value={v.clientName} onChange={e=>setV({...v,clientName:e.target.value})}/></label><label>Название сделки<input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><label>Телефон<input required value={v.phone} onChange={e=>setV({...v,phone:e.target.value})}/></label><label>Сумма, ₸<input type="number" value={v.amount} onChange={e=>setV({...v,amount:e.target.value})}/></label><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Отмена</button><button className="button">Создать</button></div></form></Modal>}
