import { CalendarClock, CheckCircle2, Clock3, MessageSquare, Trash2, X } from "lucide-react";
import { useState } from "react";
import { useCRM } from "../store";
import type { Deal, Priority } from "../types";

export function DealDrawer({ deal, onClose }: { deal: Deal; onClose: () => void }) {
  const { state, updateDeal, addComment, addTask, deleteDeal } = useCRM(); const [tab, setTab] = useState<"details" | "activity">("details"); const [comment, setComment] = useState(""); const [taskTitle, setTaskTitle] = useState("");
  const pipeline = state.pipelines.find(p => p.id === deal.pipelineId)!; const tasks = state.tasks.filter(t => t.dealId === deal.id);
  const change = (patch: Partial<Deal>, event: string) => updateDeal(deal.id, patch, event);
  return <div className="drawer-wrap"><button className="drawer-backdrop" onClick={onClose} aria-label="Закрыть"/><aside className="drawer">
    <div className="drawer-head"><div><span className="eyebrow">Сделка #{deal.id.slice(-4)}</span><input className="title-input" value={deal.title} onChange={e => change({ title: e.target.value }, "Изменено название")} /></div><button className="icon" onClick={onClose}><X /></button></div>
    <div className="drawer-tabs"><button className={tab === "details" ? "active" : ""} onClick={() => setTab("details")}>Детали</button><button className={tab === "activity" ? "active" : ""} onClick={() => setTab("activity")}>Активность <span>{deal.comments.length + deal.events.length}</span></button></div>
    {tab === "details" ? <div className="drawer-body">
      <section className="form-grid"><label>Клиент<input value={deal.clientName} onChange={e => change({ clientName: e.target.value }, "Изменено имя клиента")} /></label><label>Телефон<input value={deal.phone} onChange={e => change({ phone: e.target.value }, "Изменён телефон")} /></label><label>Email<input value={deal.email || ""} onChange={e => change({ email: e.target.value }, "Изменён email")} /></label><label>Сумма<input type="number" value={deal.amount} onChange={e => change({ amount: +e.target.value }, "Изменена сумма")} /></label>
      <label>Воронка<select value={deal.pipelineId} onChange={e => { const p = state.pipelines.find(x => x.id === e.target.value)!; change({ pipelineId: p.id, stageId: p.stages[0].id }, "Изменена воронка"); }}><option value={pipeline.id}>{pipeline.name}</option>{state.pipelines.filter(p => p.id !== pipeline.id).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <label>Этап<select value={deal.stageId} onChange={e => change({ stageId: e.target.value }, "Изменён этап")}>{pipeline.stages.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label>Приоритет<select value={deal.priority} onChange={e => change({ priority: e.target.value as Priority }, "Изменён приоритет")}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="urgent">Срочный</option></select></label>
      <label>Следующий контакт<input type="datetime-local" value={deal.nextContact?.slice(0,16) || ""} onChange={e => change({ nextContact: e.target.value ? new Date(e.target.value).toISOString() : undefined }, e.target.value ? "Назначен следующий контакт" : "Следующий контакт очищен")} /></label></section>
      <section><h3>Теги</h3><div className="tag-picker">{state.tags.map(t => <button key={t.id} className={deal.tagIds.includes(t.id) ? "tag-choice selected" : "tag-choice"} onClick={() => change({ tagIds: deal.tagIds.includes(t.id) ? deal.tagIds.filter(x => x !== t.id) : [...deal.tagIds, t.id] }, "Изменены теги")}><i style={{ background: t.color }}/>{t.name}</button>)}</div></section>
      <section><h3>Дополнительные поля</h3><div className="form-grid">{state.customFields.map(f => <label key={f.id}>{f.name}{f.type === "checkbox" ? <input type="checkbox" checked={Boolean(deal.custom[f.id])} onChange={e => change({ custom: { ...deal.custom, [f.id]: e.target.checked } }, `Изменено поле «${f.name}»`)} /> : f.type === "select" ? <select value={String(deal.custom[f.id] || "")} onChange={e => change({ custom: { ...deal.custom, [f.id]: e.target.value } }, `Изменено поле «${f.name}»`)}><option value="">Не выбрано</option>{f.options?.map(o => <option key={o}>{o}</option>)}</select> : <input type={f.type === "date" ? "date" : f.type === "number" || f.type === "money" ? "number" : "text"} value={String(deal.custom[f.id] || "")} onChange={e => change({ custom: { ...deal.custom, [f.id]: e.target.value } }, `Изменено поле «${f.name}»`)} />}</label>)}</div></section>
      <section><h3>Новая задача</h3><div className="inline-form"><input value={taskTitle} onChange={e => setTaskTitle(e.target.value)} placeholder="Например, отправить расчёт"/><button className="button secondary" onClick={() => { if (!taskTitle) return; addTask({ dealId: deal.id, title: taskTitle, dueAt: new Date(Date.now()+86400000).toISOString() }); setTaskTitle(""); }}>Добавить</button></div>{tasks.map(t => <div className="mini-task" key={t.id}><CheckCircle2 />{t.title}<small>{new Date(t.dueAt).toLocaleDateString("ru-RU")}</small></div>)}</section>
      <button className="danger-link" onClick={() => { if (confirm("Удалить сделку?")) { deleteDeal(deal.id); onClose(); } }}><Trash2/>Удалить сделку</button>
    </div> : <div className="drawer-body activity">
      <section><h3>Комментарий</h3><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="Зафиксируйте результат разговора…"/><button className="button" onClick={() => { if (comment.trim()) { addComment(deal.id, comment.trim()); setComment(""); } }}>Добавить комментарий</button></section>
      {[...deal.events.map(e => ({...e, kind:"event"})), ...deal.comments.map(c => ({...c, kind:"comment"}))].sort((a,b) => +new Date(b.createdAt)-+new Date(a.createdAt)).map(item => <div className="timeline" key={item.id}><span>{item.kind === "comment" ? <MessageSquare/> : item.text.includes("контакт") ? <CalendarClock/> : <Clock3/>}</span><div><strong>{item.kind === "comment" ? "Комментарий" : item.text}</strong>{item.kind === "comment" && <p>{item.text}</p>}<small>{new Date(item.createdAt).toLocaleString("ru-RU")}</small></div></div>)}
    </div>}
  </aside></div>;
}
